'use client';
import {useState} from 'react';
import {Leaf,UserRound,ShieldCheck,LogOut,ArrowRight,Save,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Account,AccountResponse} from '@/lib/personal-contract';
import {apiJson} from '@/lib/client-api';
import {toast} from 'sonner';
export function AccountPage({account,onChange,onPortfolio,onReviews}:{account:Account|null;onChange:(a:Account)=>void;onPortfolio:()=>void;onReviews:()=>void}){
 const [name,setName]=useState(account?.displayName??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{const r=await apiJson<AccountResponse>('/api/account',{method:'POST',body:JSON.stringify({displayName:name})});if(r.account)onChange(r.account);toast.success('Your profile is saved.')}catch(e){setError(e instanceof Error?e.message:'Could not save your profile.')}finally{setBusy(false)}}
 if(!account)return <section className="account-welcome panel"><span className="account-emblem"><Leaf size={32}/></span><div className="eyebrow">YOUR PERSONAL RESEARCH SPACE</div><h1>Make room for your ideas.</h1><p>Create your HyperGreen account to save portfolio simulations, keep your data private, and follow the evidence you flag for review.</p><a className="button-link account-signin" href="/signin-with-chatgpt?return_to=%2F%23account" target="_top">Sign up or sign in with ChatGPT <ArrowRight size={17}/></a><small>Your first sign-in creates your personal workspace.</small></section>;
 return <><div className="page-heading"><div><div className="eyebrow">YOUR HYPERGREEN ACCOUNT</div><h1>A workspace of your own.</h1><p>Your simulations, imported evidence, and review reports stay connected to your account.</p></div><a className="button-link subtle-link" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/>Sign out</a></div><div className="account-grid"><section className="panel account-profile"><div className="account-profile-head"><span>{account.displayName.slice(0,2).toUpperCase()}</span><div><h2>{account.displayName}</h2><p>{account.email}</p></div></div><form onSubmit={e=>{e.preventDefault();save()}}><label htmlFor="account-name">Display name</label><Input id="account-name" value={name} minLength={2} maxLength={60} onChange={e=>setName(e.target.value)} required/><label>Sign-in method</label><div className="account-method"><ShieldCheck size={18}/><div><b>ChatGPT</b><small>Your identity is managed by your ChatGPT account.</small></div></div><div className="account-role"><span>Workspace role</span><b>{account.reviewer?'Research reviewer':'Research member'}</b></div>{error&&<p className="error-note" role="alert">{error}</p>}<Button type="submit" disabled={busy||name.trim().length<2}>{busy?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>}Save profile</Button></form></section><div className="account-links"><button className="panel" onClick={onPortfolio}><UserRound size={22}/><h2>Your portfolio simulations</h2><p>Create up to 20 named simulations. Save allocations, capital, position limits, and scoring weights.</p><span>Open your simulations <ArrowRight size={16}/></span></button><button className="panel" onClick={onReviews}><ShieldCheck size={22}/><h2>Your evidence reviews</h2><p>Flag questionable data and follow the human review, from the original report to the final decision.</p><span>Open review centre <ArrowRight size={16}/></span></button></div></div></>
}
