'use client';
import library from '@/lib/research/manifest.json';
import {useEffect,useRef,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {Leaf,ArrowUp,Mic,Square,Check,Database,ArrowUpRight,MessageSquare,AudioLines,LoaderCircle,AlertCircle,Link2,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {DataBundle} from '@/lib/data-contract';
import {ResearchContext,AgentReply,AgentStatus} from '@/lib/agent-contract';
import {download} from '@/lib/hypergreen';
import {useVoice} from './use-voice';
type Message={id:string;role:'user'|'assistant';content:string;reply?:AgentReply;voice?:boolean};
import {apiJson} from '@/lib/client-api';

const prompts=[{title:'Compare companies',text:'Compare Microsoft and Apple using the available evidence. What is missing?',icon:Leaf},{title:'Review my portfolio',text:'Review my current net-zero portfolio. Explain concentration risks and evidence gaps.',icon:ShieldCheck},{title:'Find the next data gap',text:'What data is available here, and what do I still need for a defensible sustainability backtest?',icon:Database}];
export function ResearchAssistant({bundle,context,ready,onSources}:{bundle:DataBundle|null;context:ResearchContext;ready:boolean;onSources:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [status,setStatus]=useState<{textConfigured:boolean;voiceConfigured:boolean;model:string}|null>(null);
 const controller=useRef<AbortController|null>(null),inflight=useRef(false),messagesRef=useRef(messages),bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{messagesRef.current=messages},[messages]);
 useEffect(()=>{const c=new AbortController();apiJson<AgentStatus>('/api/agent',{signal:c.signal}).then(setStatus).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>{c.abort();controller.current?.abort()}},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,busy]);
 async function ask(question:string,voice=false){
  if(!ready||inflight.current)throw new Error('Please wait for the current research check to finish.');
  inflight.current=true;setBusy(true);setError('');
  const history=[...messagesRef.current.slice(-16).map(m=>({role:m.role,content:m.content.slice(0,8000)})),{role:'user' as const,content:question}];
  const c=new AbortController();controller.current=c;
  setMessages(prev=>[...prev,{id:crypto.randomUUID(),role:'user',content:question,voice}]);
  try{const reply=await apiJson<AgentReply>('/api/agent',{method:'POST',body:JSON.stringify({messages:history,context}),signal:c.signal}) as AgentReply;if(c.signal.aborted)throw new Error('Research stopped.');setMessages(prev=>[...prev,{id:crypto.randomUUID(),role:'assistant',content:reply.answer,reply,voice}]);return reply}
  catch(e){const message=c.signal.aborted?'Research stopped. You can edit or resend your question.':e instanceof Error?e.message:'Research is unavailable.';if(!voice)setDraft(question);setError(message);throw new Error(message)}
  finally{inflight.current=false;setBusy(false);controller.current=null}
 }
 const voice=useVoice({ask,stopResearch:()=>controller.current?.abort()});
 async function submit(text=draft){const question=text.trim();if(!question||busy||!ready)return;setDraft('');try{await ask(question)}catch{}}
 const last=messages.filter(m=>m.reply).at(-1)?.reply;
 const enabled=ready&&status?.textConfigured!==false;
 const recordCount=bundle?Object.values(bundle).filter(Array.isArray).reduce((n,v)=>n+v.length,0):24;
 return <><div className="page-heading"><div><div className="eyebrow">YOUR RESEARCH PARTNER</div><h1>A little clarity. A greener perspective.</h1><p>Explore the evidence, challenge assumptions, and ask better questions.</p></div><span className="assistant-powered"><span/>{status?.textConfigured?'MiniMax connected':'Research assistant'}</span></div>
 <div className="assistant-grid"><section className="assistant-conversation panel"><header className="conversation-header"><div className="assistant-identity"><span className="assistant-mark"><Leaf size={22}/></span><div><b>HyperGreen assistant</b><small>{busy?'Checking your research…':voice.state==='active'?'Voice conversation active':'Grounded in your workspace'}</small></div></div><Button variant="ghost" size="sm" disabled={busy||voice.state!=='idle'||!messages.length} onClick={()=>{setMessages([]);setError('')}}>New chat</Button></header>
 <div className="conversation-scroll" role="log" aria-label="Research conversation" aria-live="polite">{!messages.length?<div className="assistant-welcome"><div className="assistant-orbit"><Leaf size={34} strokeWidth={1.4}/><span className="orbit-dot"/></div><span className="eyebrow">EVIDENCE BEFORE CONCLUSIONS</span><h2>What would you like<br/>to understand?</h2><p>I can explore company data, explain the scoring framework, and help you think through a net-zero portfolio.</p><div className="prompt-cards">{prompts.map(p=><button key={p.title} disabled={!enabled||busy} onClick={()=>submit(p.text)}><p.icon size={18}/><b>{p.title}</b><ArrowUpRight size={16}/></button>)}</div></div>:messages.map(m=><article key={m.id} className={`chat-message ${m.role}`}><div className="message-byline">{m.role==='assistant'?<Leaf size={15}/>:<MessageSquare size={14}/>}<b>{m.role==='assistant'?'HyperGreen':'You'}</b>{m.voice&&<span><AudioLines size={13}/>Voice</span>}</div><div className="message-content"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{table:({children})=><div className="answer-table"><table>{children}</table></div>,img:()=>null,a:({href,children})=><a href={href?.startsWith('https://')?href:undefined} target="_blank" rel="noopener noreferrer">{children}</a>}}>{m.content}</ReactMarkdown></div>{m.reply&&<div className="message-foot"><span><Check size={13}/>{m.reply.checks.length} evidence checks</span><span>{m.reply.dataset.demo?'Synthetic demo data':'Source evidence'}</span>{m.reply.limited&&<span>Response length limit reached</span>}</div>}</article>)}{busy&&<div className="thinking"><LoaderCircle size={17} className="spin"/><span>Reading the workspace and checking evidence…</span></div>}<div ref={bottom}/></div>
 {(error||voice.error)&&<div className="assistant-error" role="alert"><AlertCircle size={16}/><span>{error||voice.error}</span></div>}
 {voice.state!=='idle'&&<div className="voice-live"><div className="voice-bars"><i/><i/><i/><i/><i/></div><div><b>{voice.state==='connecting'?'Connecting your microphone…':voice.researching?'Checking the evidence…':'Voice is on'}</b><small>{voice.transcript||'Speak naturally. You can interrupt the assistant.'}</small></div><Button variant="outline" onClick={voice.stop}><Square size={13}/>End voice</Button></div>}
 <form className="assistant-composer" onSubmit={e=>{e.preventDefault();submit()}}><textarea value={draft} maxLength={8000} rows={2} onChange={e=>setDraft(e.target.value)} placeholder={ready?'Ask about companies, evidence, or your portfolio…':'Loading your private workspace…'} aria-label="Message the research assistant" disabled={!enabled||voice.state!=='idle'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}}/><div className="composer-actions"><span><Database size={13}/>{bundle?'Your imported data':'Demo data'}</span><div><Button type="button" variant="ghost" disabled={!enabled||busy||status?.voiceConfigured===false||voice.state!=='idle'} onClick={voice.start} aria-label="Start voice chat"><Mic size={16}/><span>Voice chat</span></Button>{busy?<Button type="button" variant="outline" onClick={()=>controller.current?.abort()} aria-label="Stop research"><Square size={15}/></Button>:<Button className="send-button" type="submit" disabled={!draft.trim()||!enabled||voice.state!=='idle'} aria-label="Send message"><ArrowUp size={18}/></Button>}</div></div></form><p className="assistant-disclosure">Questions and relevant records go to MiniMax. Voice sends microphone audio and research answers to Inworld. Audio is not stored by HyperGreen.</p></section>
 <aside className="assistant-context"><section className="context-card"><div className="context-title"><Database size={17}/><h3>Connected context</h3></div><span className={`dataset-status ${bundle?'imported':''}`}>{context.datasetId===library.id?'GATHERED RESEARCH':bundle?'PRIVATE DATASET':'ILLUSTRATIVE DATA'}</span><h4>{bundle?.label??'Demonstration workspace'}</h4><p>{context.datasetId===library.id?'The assistant can query the gathered research library. Scores remain unknown until reviewed; source and mapping limits stay visible.':bundle?'Your private import and the gathered research library are available to your assistant. Evidence is not independently verified.':'Demonstration metrics are synthetic. Gathered source evidence is available separately through the research tools.'}</p><dl><div><dt>Companies</dt><dd>{bundle?.companies.length??24}</dd></div><div><dt>Workspace records</dt><dd>{recordCount.toLocaleString()}</dd></div><div><dt>Gathered records</dt><dd>{library.totalRecords.toLocaleString()}</dd></div><div><dt>Access</dt><dd>Read only</dd></div></dl><button className="text-link" onClick={onSources}>Manage your data <ArrowUpRight size={14}/></button></section>
 <section className="context-card"><div className="context-title"><ShieldCheck size={17}/><h3>Evidence trail</h3></div>{last?<ol className="evidence-trail">{last.checks.map((c,i)=><li key={i}><Check size={13}/><div><b>{c.tool.replaceAll('_',' ')}</b><small>{c.records===null?'Context verified':`${c.records} records inspected`}</small>{c.sourceIds.length>0&&<small>{c.sourceIds.slice(0,3).join(' · ')}</small>}</div></li>)}</ol>:<p>Each answer shows which data the assistant inspected. Missing evidence stays visible.</p>}{last&&<Button variant="ghost" size="sm" onClick={()=>download('hypergreen-research-answer.md',`${last.answer}\n\nDataset: ${last.dataset.label}\nChecks: ${last.checks.map(c=>c.tool).join(', ')}`,'text/markdown')}>Export answer</Button>}</section>
 <section className="context-card mcp-context"><div className="context-title"><Link2 size={17}/><h3>Connect your research</h3></div><p>A read-only MCP data server is included for company queries, source discovery, and evidence records.</p><a className="text-link" href="/mcp-guide.md" target="_blank" rel="noopener noreferrer">Connection guide <ArrowUpRight size={14}/></a><small>External client sign-in setup is required.</small></section></aside></div></>
}
