import {z} from 'zod';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10)===v,'Use a valid YYYY-MM-DD date');
const month=z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/);
const text=z.string().trim().min(1).max(400);
const num=z.number().finite();
export const companySchema=z.object({ticker:text.max(20),name:text,sector:text,cik:z.string().regex(/^\d{10}$/),scores:z.array(num.min(0).max(100).nullable()).length(4),intensity:num.min(0).nullable(),reduction:num.min(-100).nullable(),coverage:num.min(0).max(100),target:z.enum(['Validated','Committed','None disclosed','Unknown']),year:z.number().int().min(1900).max(2100),availableDate:date,source:text});
const observation=z.object({entityId:text,metric:text,value:num.nullable(),unit:text,periodEnd:date,availableDate:date,sourceId:text,basis:z.enum(['reported','estimated','target','scenario']),boundary:z.string().max(400).optional()});
const returns=z.object({ticker:text,month,totalReturn:num.min(-1),sourceId:text});
const factors=z.object({month,mktRf:num,smb:num,hml:num,rmw:num,cma:num,mom:num,rf:num,sourceId:text});
export const bundleSchema=z.object({schemaVersion:z.literal('1.0'),label:text,companies:z.array(companySchema).max(2000).default([]),observations:z.array(observation).max(50000).default([]),monthlyReturns:z.array(returns).max(100000).default([]),factors:z.array(factors).max(2000).default([]),holdings:z.array(z.object({ticker:text,snapshotDate:date,availableDate:date,weight:num.min(0).max(1),sourceId:text})).max(100000).default([]),facilities:z.array(z.object({assetId:text,name:text,latitude:num.min(-90).max(90),longitude:num.min(-180).max(180),sourceId:text})).max(20000).default([]),ownership:z.array(z.object({assetId:text,entityId:text,validFrom:date,validTo:date.nullable(),share:num.min(0).max(1),sourceId:text})).max(20000).default([]),scenarios:z.array(z.object({scenario:text,region:text,variable:text,year:z.number().int(),value:num,unit:text,sourceId:text})).max(20000).default([]),documents:z.array(z.object({entityId:text,title:text,url:z.string().url().refine(v=>v.startsWith('https://'),'HTTPS URLs only'),publishedDate:date,sourceId:text})).max(5000).default([])}).strict().superRefine((b,ctx)=>{const unique=<T,>(rows:T[],key:(x:T)=>string,label:string)=>{const seen=new Set();for(const r of rows){const k=key(r);if(seen.has(k)){ctx.addIssue({code:'custom',message:`Duplicate ${label}: ${k}`});break;}seen.add(k);}};unique(b.companies,c=>c.ticker,'company ticker');unique(b.monthlyReturns,r=>`${r.ticker}/${r.month}`,'monthly return');unique(b.factors,r=>r.month,'factor month');unique(b.holdings,r=>`${r.ticker}/${r.snapshotDate}`,'holding');if(!Object.entries(b).some(([,v])=>Array.isArray(v)&&v.length))ctx.addIssue({code:'custom',message:'The bundle must contain at least one record.'});});
export type DataBundle=z.infer<typeof bundleSchema>;
export function parseBundle(value:unknown):DataBundle{return bundleSchema.parse(value);}
export const importExample={schemaVersion:'1.0',label:'My company research',companies:[{ticker:'EXAMPLE',name:'Example company',sector:'Industrials',cik:'0000000001',scores:[75,80,null,70],intensity:120,reduction:-12,coverage:75,target:'Unknown',year:2025,availableDate:'2026-06-30',source:'Replace with your evidence source'}],observations:[],monthlyReturns:[],factors:[],holdings:[],facilities:[],ownership:[],scenarios:[],documents:[]};
